# Generated by Django 4.1.6 on 2023-03-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coinbalance_first_transaction_made'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinbalance',
            old_name='is_validated',
            new_name='is_valid',
        ),
    ]
