# Generated by Django 2.2 on 2022-11-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221012_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
