# Generated by Django 2.2 on 2023-01-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221208_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinbalance',
            name='first_transaction_made',
            field=models.BooleanField(default=False),
        ),
    ]
