# Generated by Django 4.1.6 on 2023-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_administrator_user_alter_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinbalance',
            name='first_transaction_made',
        ),
        migrations.AddField(
            model_name='coinbalance',
            name='transactions_made',
            field=models.IntegerField(default=False),
        ),
    ]
