# Generated by Django 4.1.6 on 2023-06-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='Sin descripción', max_length=300),
        ),
    ]
