# Generated by Django 4.1.6 on 2023-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_coinbalance_first_transaction_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='is validated'),
        ),
    ]
